[package]
name = "golem"
version = "0.1.6"
authors = ["Ryan Goldstein <ryan@ryanisaacg.com>"]
description = "A (mostly) safe library for graphics programming"
categories = ["game-development", "web-programming", "graphics"]
keywords = ["gl", "opengl", "webgl", "graphics",]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/ryanisaacg/golem"
readme = "README.md"

[features]
stdweb = ["std_web", "glow/stdweb"]
web-sys = ["web_sys", "glow/web-sys"]
std = []

[dependencies]
bytemuck = "1"
glow = "0.5"
log = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
raw-window-handle = "0.3"
std_web = { package = "stdweb", version = "=0.4.20", optional = true }
web_sys = { package = "web-sys", version = "0.3.22", optional = true, features = [
    'Document',
    'Element',
    'HtmlCanvasElement',
    'HtmlElement',
    'Node',
    'Window',
] }

[dev-dependencies]
blinds = { version = "0.1.0", default-features = false, features = ["gl"] }
nalgebra-glm = "0.7.0"
